# Generated by Django 5.2.8 on 2025-11-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Системное имя меню. Используется в template tag {% draw_menu 'name' %}", max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Человекочитаемое название (для админки)', max_length=200)),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название пункта')),
                ('url', models.CharField(blank=True, help_text='Явный URL (например /contacts/). Если указан named_url, он приоритетнее.', max_length=255)),
                ('named_url', models.CharField(blank=True, help_text="Имя url из urls.py (reverse). Например: 'contacts:list'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu', verbose_name='Меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ('menu', 'parent__id', 'order', 'id'),
            },
        ),
    ]
